### ISSUE TITLE
MEM not initialised in "mount.sdfs" under Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by tony-travis** [opendedup/sdfs#18]
I couldn't mount an "sdfs" filesystem under Ubuntu 16.04 LTS:

`mount.sdfs dedup /mnt`
`Invalid maximum heap size: -XmxM`
`Cannot create Java VM`
`Service exit with a return value of 1`

Tracing the execution with "bash -x" I can see that this is because $MEM is not initialised, but it can be set in the environment:

`export MEM=1024`
`mount.sdfs dedup /mnt`
`Running Program SDFS Version 3.3.6`
`reading config file = /etc/sdfs/dedup-volume-cfg.xml`
`Loading BloomFilters |))))))))))))))))))))))))))))))))))))))))))))))))))| 100% `
`Waiting for last bloomfilters to load`
`Loaded entries 0`
`Mounted Filesystem`

**Comment by opendedup** [comment]
Tony - OpenDedupe does work with 16.04 but I have seen this issue before
but have been unable to locate the cause. The variable does get iniciated
the script. As a work around exit the bash shell and open an new shell and
retry the mount.

Sam

**Comment by billccn** [comment]
The bug is in [this line](https://github.com/opendedup/sdfs/blob/master/install-packages/deb/usr/share/sdfs/mount.sdfs#L11), `{$1:0:1}` is not a valid expansion (`$ should be on the outside`).

The script also suggests a `-z` parameter which can be used to override the `-Xmx`, but if you actually use it (after fixing the above expansion), the Java code would reject this parameter...

**Comment by opendedup** [comment]
Thanks ! I will fix it

**Comment by alhimik45** [comment]
This issue still exists. Got it on this package http://www.opendedup.org/downloads/sdfs-latest.deb on Ubuntu 20.04

**Comment by richman1000000** [comment]
I'm using modified script.
to enable HugePages+ little speed up during boot and CPU consumption reduction
[mount.sdfs.txt](https://github.com/opendedup/sdfs/files/5772205/mount.sdfs.txt)
